# Generated by Django 4.2 on 2023-04-24 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_photo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='description',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
    ]
