# Generated by Django 4.2 on 2023-04-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.JSONField(),
        ),
    ]
